#!/usr/bin/env node
/**
 * Rebuilds src/utils/brandsWithLogos.generated.ts from the image files.
 *
 * WHY THIS EXISTS AT ALL. The matcher recognises a brand ONLY when there is
 * an image to show for it - recognising a name in order to draw its initials
 * buys nothing the app cannot already do for any text. So the list of
 * recognised brands has to be derived from the directory, not maintained
 * beside it, or the two drift and a name matches with nothing to render.
 *
 * WHY IT IS BEING WRITTEN NOW. The generated file has named this script as
 * its source since it was first committed, and the script itself never was:
 * `git log --all -- scripts/discover-brands.mjs` is empty. Adding a logo
 * therefore meant hand-editing a file whose header says "do not edit by
 * hand", and forgetting to meant shipping an image nothing would ever match.
 *
 *   node scripts/discover-brands.mjs            # rewrite the manifest
 *   node scripts/discover-brands.mjs --check    # fail if it is out of date
 */

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const BRANDS_DIR = join(ROOT, 'apps', 'web', 'src', 'assets', 'brands');
const OUT = join(ROOT, 'apps', 'web', 'src', 'utils', 'brandsWithLogos.generated.ts');

/* The extensions BrandMark's import.meta.glob actually picks up. These two
   lists ARE the same list, and drift between them is silent in the worst
   direction: a file the manifest advertises but the glob skips makes a brand
   recognised with no image to draw. jpg and webp were added here and there
   together. */
const USABLE = /\.(png|svg|jpe?g|webp)$/i;

const nameOf = (file) =>
  file
    .replace(USABLE, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, ' ')
    .trim();

const files = readdirSync(BRANDS_DIR).filter((f) => USABLE.test(f));
const ignored = readdirSync(BRANDS_DIR).filter((f) => !USABLE.test(f));

const names = [...new Set(files.map(nameOf))].filter(Boolean).sort();

const body = `/**
 * GENERATED by scripts/discover-brands.mjs - do not edit by hand.
 *
 * Every brand that has a logo file in src/assets/brands, as a name the
 * matcher can look for. Derived from the files themselves, so a brand can
 * never be recognised without an image to show for it.
 */
export const BRANDS_WITH_LOGOS: readonly string[] = [
${names.map((n) => `  '${n}',`).join('\n')}
];
`;

const current = (() => {
  try { return readFileSync(OUT, 'utf8'); } catch { return ''; }
})();

if (process.argv.includes('--check')) {
  if (current === body) {
    console.log(`up to date: ${names.length} brands`);
    process.exit(0);
  }
  console.error('OUT OF DATE - run: node scripts/discover-brands.mjs');
  const had = new Set([...current.matchAll(/'([^']+)'/g)].map((m) => m[1]));
  const now = new Set(names);
  const added = names.filter((n) => !had.has(n));
  const gone = [...had].filter((n) => !now.has(n));
  if (added.length) console.error(`  files present but not listed: ${added.join(', ')}`);
  if (gone.length) console.error(`  listed but no file: ${gone.join(', ')}`);
  process.exit(1);
}

writeFileSync(OUT, body);

const before = [...current.matchAll(/'([^']+)'/g)].map((m) => m[1]);
const added = names.filter((n) => !before.includes(n));
const removed = before.filter((n) => !names.includes(n));

console.log(`wrote ${names.length} brands to brandsWithLogos.generated.ts`);
if (added.length) console.log(`  added:   ${added.join(', ')}`);
if (removed.length) console.log(`  removed: ${removed.join(', ')}`);
if (!added.length && !removed.length) console.log('  no change');
if (ignored.length) console.log(`  ignored (not png/svg): ${ignored.join(', ')}`);
